image:
  file: gitpod.Dockerfile
tasks:
  - name: tailscaled
    command: |
      sudo tailscaled
  - name: tailscale
    command: |
      # hostname = gitpod_<user>_<org>_<repo>
      sudo -E tailscale up --hostname "gitpod_${GITPOD_GIT_USER_NAME}_$(echo $GITPOD_WORKSPACE_CONTEXT | jq -r .repository.owner)_$(echo ${GITPOD_WORKSPACE_CONTEXT} | jq -r .repository.name)" \
                           --authkey "${TAILSCALE_AUTHKEY}"

experimentalNetwork: true
